//! Serving a frontend bundle to a webview, from Rust.
//!
//! # The gap this closes
//!
//! Every page in this app used to be a single HTML string handed to
//! `loadData(html, 'text/html', 'UTF-8', 'https://localhost/')`. That is fine
//! for markup Rust generates and hopeless for a frontend anyone builds: the
//! moment `index.html` asks for `/assets/index-a3f2.js`, a font, or a
//! code-split chunk, the request resolves against `https://localhost/` and
//! there is nothing there to answer it.
//!
//! ArkWeb has a real custom-protocol API, and it is the same shape as Tauri's:
//!
//! ```text
//! WebviewController.customizeSchemes([{schemeName: 'splash', ...}])  register
//! controller.setWebSchemeHandler('splash', handler)                  install
//! handler.onRequestStart((req, res) => boolean)                      serve
//! ```
//!
//! ArkTS owns those three calls because they are ArkTS APIs. What it does not
//! own is *what gets served*: it asks this module for a URL and streams back
//! whatever comes out.
//!
//! # Where the bytes come from
//!
//! Compiled in. `build.rs` walks the frontend directory —
//! `SPLASH_FRONTEND_DIR`, or `assets/app` — and embeds everything under it,
//! nested folders and content-hashed filenames included. Point it at a
//! bundler's `dist/` and that is the app.
//!
//! The obvious alternative — push a `dist/` into the app sandbox and serve from
//! there — does not work, and the reason is already written down in
//! `bridge.rs`: `hdc`'s file push resolves outside the app's mount namespace,
//! so the file never arrives where the app can read it. Live reloading instead
//! goes through a dev server; see `SPLASH_DEV_SERVER`.
//!
//! # The shim
//!
//! A page Rust generated gets the bridge shim prepended to its markup. A page
//! Rust did not generate cannot, so the shim is served here as
//! `/__splash.js` and the page includes it like any other script. That is a
//! contract the frontend has to honour, and it is deliberately explicit: the
//! alternative is rewriting someone else's HTML on the way past.

/// A served response.
pub struct Asset {
    pub mime: &'static str,
    pub body: Vec<u8>,
    pub status: u16,
}

/// The scheme this app answers for. Registered by ArkTS before the web engine
/// starts; the two sides have to agree and a mismatch is silent.
pub const SCHEME: &str = "splash";

/// Everything under the frontend directory, generated by `build.rs`.
///
/// This used to be five filenames written out by hand, which is fine for a
/// fixture and useless for a real app: bundlers emit content-hashed names like
/// `index-a3f2c9.js` in subdirectories, and both change on every build. Set
/// `SPLASH_FRONTEND_DIR` to a `dist/` and whatever is in it ships as-is.
include!(concat!(env!("OUT_DIR"), "/bundle.rs"));

/// The dev server this build points at, if any.
///
/// Set `SPLASH_DEV_SERVER=http://192.168.1.20:5173` at build time and an app
/// slot navigates there instead of to `splash://app`. The frontend then comes
/// from the bundler, with its live reload intact, and a CSS edit shows up on
/// the phone without rebuilding anything.
///
/// The embedded bundle is still compiled in, so a build pointed at a server
/// that is not running is a page that fails to load rather than an app with no
/// frontend at all.
///
/// Not a runtime switch. A release build with no `SPLASH_DEV_SERVER` has no
/// notion of one, which is the point: a debug convenience that can be turned on
/// in a shipped app is a way for someone else's server to become your frontend.
pub fn dev_server() -> Option<&'static str> {
    match option_env!("SPLASH_DEV_SERVER") {
        Some(s) if !s.is_empty() => Some(s.trim_end_matches('/')),
        _ => None,
    }
}

/// The origin an app slot's document should be on.
///
/// `splash://app` normally; the dev server's origin when this build has one.
pub fn app_origin() -> String {
    match dev_server() {
        Some(url) => origin_of(url),
        None => format!("{SCHEME}://app"),
    }
}

/// `http://host:5173/some/path` -> `http://host:5173`.
pub fn origin_of(url: &str) -> String {
    match url.find("://") {
        Some(i) => match url[i + 3..].find('/') {
            Some(j) => url[..i + 3 + j].to_string(),
            None => url.to_string(),
        },
        None => url.to_string(),
    }
}

/// Resolve a request URL to bytes.
///
/// Returns a 404 asset rather than `None` for an unknown path. ArkWeb has no
/// default resolver for a custom scheme, so declining to handle a request does
/// not produce a normal 404 — it produces a request that nothing ever answers,
/// which the page sees as a hang rather than a miss.
pub fn get(url: &str) -> Asset {
    let path = normalise(url);

    if path == "/__splash.js" {
        return Asset {
            mime: "text/javascript",
            body: crate::bridge::SHIM_JS.as_bytes().to_vec(),
            status: 200,
        };
    }

    for (p, mime, body) in BUNDLE {
        if *p == path {
            return Asset {
                mime,
                body: body.to_vec(),
                status: 200,
            };
        }
    }

    crate::log(&format!("assets: 404 {path}"));
    Asset {
        mime: "text/plain",
        body: format!("not found: {path}").into_bytes(),
        status: 404,
    }
}

/// `splash://app/a/b?q=1#frag` -> `/a/b`.
///
/// Traversal is not resolved, it is rejected: any path containing a `..`
/// segment becomes `/`, which then serves the index rather than reaching
/// upward. There is no filesystem behind this today, but there will be, and a
/// normaliser that silently resolves `..` is how that becomes a bug later.
fn normalise(url: &str) -> String {
    let rest = url.split_once("://").map(|(_, r)| r).unwrap_or(url);
    // Drop the authority ("app"), keep the path.
    let path = match rest.find('/') {
        Some(i) => &rest[i..],
        None => "/",
    };
    let path = path.split(['?', '#']).next().unwrap_or("/");
    if path.split('/').any(|seg| seg == "..") {
        crate::log(&format!("assets: rejected traversal in {url:?}"));
        return "/index.html".to_string();
    }
    if path.is_empty() || path == "/" {
        return "/index.html".to_string();
    }
    path.to_string()
}

/// Check path handling on the device, and log the result.
///
/// The `#[cfg(test)]` cases below cannot be executed anywhere useful: the crate
/// only builds for `aarch64-unknown-linux-ohos`, so `cargo test` produces a
/// binary the host cannot run, and pushing it to the phone fails because
/// SELinux refuses to exec from `/data/local/tmp`. Tests that compile but never
/// run are assertions, not evidence — and traversal rejection is exactly the
/// kind of check that must not be taken on trust.
///
/// So the same cases also run at startup, where the code actually lives. Called
/// from `mount`.
pub fn self_test() {
    let cases: &[(&str, &str)] = &[
        ("splash://app/", "/index.html"),
        ("splash://app", "/index.html"),
        ("splash://app/app.js", "/app.js"),
        ("splash://app/app.js?v=2", "/app.js"),
        ("splash://app/a/b.css#x", "/a/b.css"),
        // Traversal is refused, not resolved.
        ("splash://app/../secret", "/index.html"),
        ("splash://app/a/../../etc/passwd", "/index.html"),
    ];
    let mut bad = 0;
    for (input, want) in cases {
        let got = normalise(input);
        if got != *want {
            bad += 1;
            crate::log(&format!(
                "assets selftest: {input:?} -> {got:?}, expected {want:?}"
            ));
        }
    }
    for (input, want) in [
        ("http://1.2.3.4:5173", "http://1.2.3.4:5173"),
        ("http://1.2.3.4:5173/", "http://1.2.3.4:5173"),
        ("http://1.2.3.4:5173/a/b", "http://1.2.3.4:5173"),
        ("splash://app/index.html", "splash://app"),
    ] {
        if origin_of(input) != want {
            bad += 1;
            crate::log(&format!(
                "assets selftest: origin_of({input:?}) -> {:?}, expected {want:?}",
                origin_of(input)
            ));
        }
    }
    if bad == 0 {
        crate::log(&format!(
            "assets selftest: ok ({} paths + origins, traversal refused, dev_server={:?})",
            cases.len(),
            dev_server()
        ));
    } else {
        crate::log(&format!("assets selftest: {bad} FAILURES"));
    }
}

#[cfg(test)]
mod tests {
    use super::normalise;

    #[test]
    fn paths_normalise() {
        assert_eq!(normalise("splash://app/"), "/index.html");
        assert_eq!(normalise("splash://app"), "/index.html");
        assert_eq!(normalise("splash://app/app.js"), "/app.js");
        assert_eq!(normalise("splash://app/app.js?v=2"), "/app.js");
        assert_eq!(normalise("splash://app/a/b.css#x"), "/a/b.css");
    }

    #[test]
    fn traversal_is_refused_not_resolved() {
        assert_eq!(normalise("splash://app/../secret"), "/index.html");
        assert_eq!(normalise("splash://app/a/../../etc/passwd"), "/index.html");
    }
}
