//! Embed a frontend build into the binary.
//!
//! The asset table used to be five filenames written out by hand in
//! `assets.rs`. That is fine for a fixture and useless for a real app: every
//! bundler emits content-hashed names like `index-a3f2c9.js` and puts them in
//! subdirectories, and both change on every build. Hand-maintaining that list
//! would mean editing Rust after each `npm run build`.
//!
//! So the list is generated. This walks the frontend directory and writes a
//! table of `(url path, mime, bytes)` for everything it finds, nested folders
//! included.
//!
//! The directory is `SPLASH_FRONTEND_DIR` if set, otherwise `assets/app`. Point
//! it at a `dist/` and the bundler's output ships as-is.

use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=SPLASH_FRONTEND_DIR");
    println!("cargo:rerun-if-env-changed=SPLASH_DEV_SERVER");
    // A dev-server build still embeds the bundle, so the app has something to
    // fall back to when the server is unreachable.
    if let Ok(url) = env::var("SPLASH_DEV_SERVER") {
        println!("cargo:rustc-env=SPLASH_DEV_SERVER={url}");
    }
    generate_bundle();
}

fn generate_bundle() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dir = match env::var("SPLASH_FRONTEND_DIR") {
        Ok(d) => {
            let p = PathBuf::from(&d);
            if p.is_absolute() {
                p
            } else {
                manifest.join(p)
            }
        }
        Err(_) => manifest.join("assets/app"),
    };

    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files = Vec::new();
    collect(&dir, &dir, &mut files);
    // Sorted so the generated file is byte-identical between builds of the same
    // input. Directory order is not stable across filesystems, and an asset
    // table that reshuffles itself would make every build look changed.
    files.sort();

    if files.is_empty() {
        println!(
            "cargo:warning=no frontend files under {} — the app will serve 404 for everything. \
             Set SPLASH_FRONTEND_DIR to your bundler's output directory.",
            dir.display()
        );
    } else if !files.iter().any(|(url, _)| url == "/index.html") {
        // Not fatal: a page can be entered at any path. But a bundle with no
        // index is nearly always a wrong directory, and finding that out from a
        // blank screen on a phone is a bad way to spend an afternoon.
        println!(
            "cargo:warning={} has no index.html — is it really the bundler's output directory?",
            dir.display()
        );
    }

    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from the frontend directory. Do not edit.\n\
         pub static BUNDLE: &[(&str, &str, &[u8])] = &[\n",
    );
    for (url, path) in &files {
        let _ = writeln!(
            out,
            "    ({:?}, {:?}, include_bytes!({:?})),",
            url,
            mime_for(url),
            path.to_string_lossy()
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("bundle.rs");
    std::fs::write(&dest, out).expect("write bundle.rs");
    println!("cargo:warning=embedded {} frontend file(s)", files.len());
}

/// Walk `dir`, collecting `(url path, absolute file path)`.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let path = e.path();
        let name = e.file_name();
        let name = name.to_string_lossy();
        // Editor droppings and VCS metadata are not frontend assets, and
        // .DS_Store in particular follows any directory copied on a Mac.
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let Ok(rel) = path.strip_prefix(root) else {
                continue;
            };
            // Always forward slashes: this is a URL, not a host path, and on a
            // Windows checkout the components would otherwise arrive separated
            // by backslashes and never match a request.
            let url = format!(
                "/{}",
                rel.components()
                    .map(|c| c.as_os_str().to_string_lossy().into_owned())
                    .collect::<Vec<_>>()
                    .join("/")
            );
            out.push((url, path));
        }
    }
}

/// Content type by extension.
///
/// Getting this wrong is not cosmetic. A stylesheet served as `text/plain` is
/// ignored, and a module served as anything but a JavaScript type is refused by
/// the module loader outright — both of which present as a page that loads and
/// looks broken rather than as an error.
fn mime_for(url: &str) -> &'static str {
    let ext = url.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "html" | "htm" => "text/html",
        "js" | "mjs" | "cjs" => "text/javascript",
        "css" => "text/css",
        "json" | "map" => "application/json",
        "webmanifest" => "application/manifest+json",
        "wasm" => "application/wasm",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "mp4" => "video/mp4",
        "webm" => "video/webm",
        "mp3" => "audio/mpeg",
        "wav" => "audio/wav",
        "txt" => "text/plain",
        "xml" => "application/xml",
        _ => "application/octet-stream",
    }
}
