//! The eight wonders, and how each one's illustration is put together.
//!
//! Generated from the Flutter app's own `*_illustration.dart` files and the
//! real asset dimensions, so the numbers here are the numbers Wonderous uses
//! rather than a person's estimate of them. See `illustration.rs` for what the
//! layout rules mean.

/// Where a piece anchors inside the frame before it is translated.
#[derive(Clone, Copy, PartialEq)]
pub enum Anchor {
    Center,
    TopLeft,
    TopCenter,
    TopRight,
    BottomLeft,
    BottomCenter,
    BottomRight,
}

/// One layer of a wonder's illustration.
pub struct Piece {
    pub file: &'static str,
    /// Width / height of the source image. Wonderous reads this at runtime to
    /// place the piece; the images do not change, so it is baked in here.
    pub aspect: f32,
    /// Height as a fraction of the frame, floored by `min_h`.
    pub height_factor: f32,
    pub min_h: f32,
    pub anchor: Anchor,
    /// Translation as a fraction of the piece's own width and height.
    pub frac_x: f32,
    pub frac_y: f32,
    /// A flat translation applied on top, in vp.
    pub off_x: f32,
    pub off_y: f32,
}

pub struct Wonder {
    pub dir: &'static str,
    pub title: &'static str,
    pub region: &'static str,
    /// The small italic word above the title, if the name has one.
    pub article: &'static str,
    pub line1: &'static str,
    pub line2: &'static str,
    /// Rendered width of each line, in multiples of the font size, measured in
    /// Yeseva One itself. ArkUI cannot report a text node's laid-out width, so
    /// a box sized by a guess either wraps the word or leaves the article
    /// stranded at the margin. These are measured, not estimated.
    pub em1: f32,
    pub em2: f32,
    pub bg: u32,
    pub fg: u32,
    /// Seed for the three drifting clouds. Wonderous's own per-wonder value.
    pub cloud_seed: u32,
    pub pieces: &'static [Piece],
}

const PYRAMIDS_PIECES: &[Piece] = &[
    Piece {
        file: "moon.png",
        aspect: 1.0,
        height_factor: 0.15,
        min_h: 100.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "pyramids.png",
        aspect: 2.0086,
        height_factor: 0.5,
        min_h: 300.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: -0.15,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-back.png",
        aspect: 3.1603,
        height_factor: 0.55,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.2,
        frac_y: -0.01,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-front.png",
        aspect: 2.9724,
        height_factor: 0.55,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.09,
        frac_y: 0.02,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const GREAT_WALL_OF_CHINA_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 1.0071,
        height_factor: 0.25,
        min_h: 120.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "great-wall.png",
        aspect: 1.0769,
        height_factor: 0.65,
        min_h: 250.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: -0.15,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 0.78571,
        height_factor: 0.85,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.4,
        frac_y: 0.45,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 0.81214,
        height_factor: 1.0,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.4,
        frac_y: 0.3,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const PETRA_PIECES: &[Piece] = &[
    Piece {
        file: "moon.png",
        aspect: 1.009,
        height_factor: 0.15,
        min_h: 50.0,
        anchor: Anchor::TopCenter,
        frac_x: -0.7,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "petra.png",
        aspect: 1.4286,
        height_factor: 0.65,
        min_h: 500.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 0.61,
        height_factor: 1.0,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.6,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 0.65214,
        height_factor: 1.0,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.55,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const COLOSSEUM_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 1.0053,
        height_factor: 0.25,
        min_h: 100.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "colosseum.png",
        aspect: 1.483,
        height_factor: 0.6,
        min_h: 200.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: -0.1,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 0.51754,
        height_factor: 0.65,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.5,
        frac_y: 0.1,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 0.56071,
        height_factor: 0.75,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.5,
        frac_y: 0.25,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const CHICHEN_ITZA_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 0.57769,
        height_factor: 0.4,
        min_h: 200.0,
        anchor: Anchor::Center,
        frac_x: 0.55,
        frac_y: -0.35,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "chichen.png",
        aspect: 3.794,
        height_factor: 0.4,
        min_h: 180.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 1.0517,
        height_factor: 0.4,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.5,
        frac_y: -0.1,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 1.0499,
        height_factor: 0.65,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.4,
        frac_y: 0.2,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "top-left.png",
        aspect: 0.93902,
        height_factor: 0.65,
        min_h: 0.0,
        anchor: Anchor::TopLeft,
        frac_x: -0.4,
        frac_y: -0.4,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "top-right.png",
        aspect: 0.80098,
        height_factor: 0.65,
        min_h: 0.0,
        anchor: Anchor::TopRight,
        frac_x: 0.35,
        frac_y: -0.4,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const MACHU_PICCHU_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 0.99206,
        height_factor: 0.15,
        min_h: 100.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "machu-picchu.png",
        aspect: 1.8617,
        height_factor: 0.65,
        min_h: 230.0,
        anchor: Anchor::Center,
        frac_x: -0.05,
        frac_y: -0.12,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-back.png",
        aspect: 3.4826,
        height_factor: 0.6,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.0,
        frac_y: 0.2,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-front.png",
        aspect: 1.1885,
        height_factor: 0.6,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.35,
        frac_y: 0.4,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const TAJ_MAHAL_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 1.0,
        height_factor: 0.3,
        min_h: 140.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "taj-mahal.png",
        aspect: 1.6667,
        height_factor: 0.6,
        min_h: 230.0,
        anchor: Anchor::Center,
        frac_x: 0.0,
        frac_y: -0.15,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 0.74643,
        height_factor: 0.9,
        min_h: 0.0,
        anchor: Anchor::BottomRight,
        frac_x: 0.3,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 0.655,
        height_factor: 0.9,
        min_h: 0.0,
        anchor: Anchor::BottomLeft,
        frac_x: -0.3,
        frac_y: 0.0,
        off_x: 0.0,
        off_y: 0.0,
    },
];

const CHRIST_THE_REDEEMER_PIECES: &[Piece] = &[
    Piece {
        file: "sun.png",
        aspect: 0.98361,
        height_factor: 0.25,
        min_h: 120.0,
        anchor: Anchor::Center,
        frac_x: 0.7,
        frac_y: -1.35,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "redeemer.png",
        aspect: 1.141,
        height_factor: 1.0,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.0,
        frac_y: 0.1,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-left.png",
        aspect: 1.2647,
        height_factor: 0.65,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: -0.25,
        frac_y: 0.05,
        off_x: 0.0,
        off_y: 0.0,
    },
    Piece {
        file: "foreground-right.png",
        aspect: 1.3384,
        height_factor: 0.55,
        min_h: 0.0,
        anchor: Anchor::BottomCenter,
        frac_x: 0.35,
        frac_y: 0.2,
        off_x: 0.0,
        off_y: 0.0,
    },
];

/// In the order the app presents them.
pub const WONDERS: &[Wonder] = &[
    Wonder {
        dir: "pyramids",
        title: "Pyramids of Giza",
        region: "Egypt",
        article: "",
        line1: "Pyramids",
        line2: "of Giza",
        em1: 4.795,
        em2: 3.505,
        bg: 0xFF16184D,
        fg: 0xFF444B9B,
        cloud_seed: 15,
        pieces: PYRAMIDS_PIECES,
    },
    Wonder {
        dir: "great_wall_of_china",
        title: "Great Wall of China",
        region: "China",
        article: "the",
        line1: "Great Wall",
        line2: "of China",
        em1: 5.37,
        em2: 4.24,
        bg: 0xFF642828,
        fg: 0xFF688750,
        cloud_seed: 500,
        pieces: GREAT_WALL_OF_CHINA_PIECES,
    },
    Wonder {
        dir: "petra",
        title: "Petra",
        region: "Jordan",
        article: "",
        line1: "Petra",
        line2: "",
        em1: 2.795,
        em2: 0.0,
        bg: 0xFF444B9B,
        fg: 0xFF1B1A65,
        cloud_seed: 111,
        pieces: PETRA_PIECES,
    },
    Wonder {
        dir: "colosseum",
        title: "Colosseum",
        region: "Italy",
        article: "the",
        line1: "Colosseum",
        line2: "",
        em1: 5.45,
        em2: 0.0,
        bg: 0xFF1E736D,
        fg: 0xFF4AA39D,
        cloud_seed: 1,
        pieces: COLOSSEUM_PIECES,
    },
    Wonder {
        dir: "chichen_itza",
        title: "Chichen Itza",
        region: "Mexico",
        article: "",
        line1: "Chichen",
        line2: "Itza",
        em1: 4.075,
        em2: 1.985,
        bg: 0xFF164F2A,
        fg: 0xFFE2CFBB,
        cloud_seed: 2,
        pieces: CHICHEN_ITZA_PIECES,
    },
    Wonder {
        dir: "machu_picchu",
        title: "Machu Picchu",
        region: "Peru",
        article: "",
        line1: "Machu",
        line2: "Picchu",
        em1: 3.435,
        em2: 3.39,
        bg: 0xFF0E4064,
        fg: 0xFFC1D9D1,
        cloud_seed: 37,
        pieces: MACHU_PICCHU_PIECES,
    },
    Wonder {
        dir: "taj_mahal",
        title: "Taj Mahal",
        region: "India",
        article: "the",
        line1: "Taj",
        line2: "Mahal",
        em1: 1.57,
        em2: 3.2,
        bg: 0xFFC96454,
        fg: 0xFF642828,
        cloud_seed: 2,
        pieces: TAJ_MAHAL_PIECES,
    },
    Wonder {
        dir: "christ_the_redeemer",
        title: "Christ the Redeemer",
        region: "Brazil",
        article: "the",
        line1: "Christ",
        line2: "Redeemer",
        em1: 3.15,
        em2: 5.015,
        bg: 0xFF1C4D46,
        fg: 0xFFED7967,
        cloud_seed: 78,
        pieces: CHRIST_THE_REDEEMER_PIECES,
    },
];

/// `artifactStartYr` / `artifactEndYr` — where the search screen's time range
/// starts for each wonder, in the order `WONDERS` lists them.
pub const ARTIFACT_YEARS: &[(i32, i32)] = &[
    (-2800, -2300), // Pyramids of Giza
    (-700, 1650),   // Great Wall of China
    (-500, 500),    // Petra
    (0, 500),       // Colosseum
    (500, 1600),    // Chichen Itza
    (1200, 1700),   // Machu Picchu
    (1600, 1700),   // Taj Mahal
    (1600, 2100),   // Christ the Redeemer
];
