//! The editorial copy, from the app's own `app_en.arb`.
//!
//! 432 strings ship with Wonderous; these are the ones the wonder-details
//! screens read. Taken verbatim rather than paraphrased -- the prose is the
//! content of those screens, and rewriting it would be reproducing the layout
//! around different words.

pub struct Editorial {
    pub sub_title: &'static str,
    pub region: &'static str,
    pub history1: &'static str,
    pub history2: &'static str,
    pub construction1: &'static str,
    pub construction2: &'static str,
    pub location1: &'static str,
    pub location2: &'static str,
    pub quote_top: &'static str,
    pub quote_bottom: &'static str,
    pub quote_author: &'static str,
    pub callout1: &'static str,
    pub callout2: &'static str,
    pub video_caption: &'static str,
    pub map_caption: &'static str,
}

/// Same order as `WONDERS`.
pub const EDITORIAL: &[Editorial] = &[
    Editorial {
        sub_title: "The ancient wonder",
        region: "Cairo, Egypt",
        history1: "The Giza pyramid complex, also called the Giza necropolis, is the site on the Giza Plateau in Greater Cairo, Egypt that includes the Great Pyramid of Giza, the Pyramid of Khafre, and the Pyramid of Menkaure, along with their associated pyramid complexes and the Great Sphinx of Giza. All were built during the Fourth Dynasty of the Old Kingdom of Ancient Egypt, between 2600 and 2500 BCE.",
        history2: "The pyramids of Giza and others are thought to have been constructed to house the remains of the deceased pharaohs who ruled over Ancient Egypt. A portion of the pharaoh's spirit called his ka was believed to remain with his corpse. Proper care of the remains was necessary in order for the former Pharaoh to perform his new duties as king of the dead.",
        construction1: "Most construction theories are based on the idea that the pyramids were built by moving huge stones from a quarry and dragging and lifting them into place. In building the pyramids, the architects might have developed their techniques over time.\nThey would select a site on a relatively flat area of bedrock — not sand — which provided a stable foundation. After carefully surveying the site and laying down the first level of stones, they constructed the pyramids in horizontal levels, one on top of the other.",
        construction2: "For the Great Pyramid, most of the stone for the interior seems to have been quarried immediately to the south of the construction site. The smooth exterior of the pyramid was made of a fine grade of white limestone that was quarried across the Nile.\nTo ensure that the pyramid remained symmetrical, the exterior casing stones all had to be equal in height and width. Workers might have marked all the blocks to indicate the angle of the pyramid wall and trimmed the surfaces carefully so that the blocks fit together. During construction, the outer surface of the stone was smooth limestone; excess stone has eroded as time has passed.",
        location1: "The site is at the edges of the Western Desert, approximately 5.6 miles (9 km) west of the Nile River in the city of Giza, and about 8 miles (13 km) southwest of the city center of Cairo.",
        location2: "Currently, the pyramids are located in the northwestern side of the Western Desert, and it is considered to be one of the best recognizable and the most visited tourist attractions of the planet.",
        quote_top: "The Tallest Structures on Earth",
        quote_bottom: "Until the Advent of Modern Skyscrapers",
        quote_author: "",
        callout1: "It is theorized the pyramid not only served as a tomb for the pharaoh, but also as a storage pit for various items he would need in the afterlife.",
        callout2: "The Great Pyramid consists of an estimated 2.3 million blocks. Approximately 5.5 million tonnes of limestone, 8,000 tonnes of granite, and 500,000 tonnes of mortar were used in the construction.",
        video_caption: "“The Great Pyramids of Giza | Egypt’s Ancient Mysteries | National Geographic UK.” Youtube, uploaded by National Geographic UK.",
        map_caption: "Map showing location of Giza Pyramids in Greater Cairo, Egypt.",
    },
    Editorial {
        sub_title: "Longest structure on Earth",
        region: "China",
        history1: "The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. The total length of all sections ever built is over 13,000 miles.",
        history2: "Several walls were built from as early as the 7th century BCE, with selective stretches later joined together by Qin Shi Huang (220-206  BCE), the first emperor of China. Little of the Qin wall remains. \nLater on, many successive dynasties built and maintained multiple stretches of border walls.",
        construction1: "Transporting the large quantity of materials required for construction was difficult, so builders always tried to use local resources. Stones from the mountains were used over mountain ranges, while rammed earth was used for construction in the plains. Most of the ancient walls have eroded away over the centuries.",
        construction2: "Stones cut into rectangular shapes were used for the foundation, inner and outer brims, and gateways of the wall. \nUnder the rule of the Qing dynasty, China's borders extended beyond the walls and Mongolia was annexed into the empire, so construction was discontinued.",
        location1: "The frontier walls built by different dynasties have multiple courses. Collectively, they stretch from Liaodong in the east to Lop Lake in the west, from the present-day Sino-Russian border in the north to Tao River in the south; along an arc that roughly delineates the edge of the Mongolian steppe.",
        location2: "Apart from defense, other purposes of the Great Wall have included border controls, allowing the imposition of duties on goods transported along the Silk Road, regulation or encouragement of trade and the control of immigration and emigration.",
        quote_top: "The Longest Man-Made",
        quote_bottom: "Structure in the World",
        quote_author: "",
        callout1: "The best-known sections of the wall were built by the Ming dynasty (1368-1644).",
        callout2: "During the Ming dynasty, however, bricks were heavily used in many areas of the wall, as were materials such as tiles, lime, and stone.",
        video_caption: "“See China’s Iconic Great Wall From Above | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Great Wall of China in northern China.",
    },
    Editorial {
        sub_title: "The Lost City",
        region: "Ma’an, Jordan",
        history1: "The area around Petra has been inhabited from as early as 7000  BCE, and the Nabataeans might have settled in what would become the capital city of their kingdom as early as the 4th century BCE.\nThe trading business gained the Nabataeans considerable revenue and Petra became the focus of their wealth. The Nabataeans were accustomed to living in the barren deserts, unlike their enemies, and were able to repel attacks by taking advantage of the area's mountainous terrain.",
        history2: "Petra flourished in the 1st century CE, when its famous Al-Khazneh structure - believed to be the mausoleum of Nabataean king Aretas IV - was constructed, and its population peaked at an estimated 20,000 inhabitants.\nAccess to the city is through a 3/4 mile-long (1.2 km) gorge called the Siq, which leads directly to the Khazneh.",
        construction1: "Famous for its rock-cut architecture and water conduit system, Petra is also called the \"Red Rose City\" because of the color of the stone from which it is carved.\nAnother thing Petra is known for is its Hellenistic (“Greek”) architecture. These influences can be seen in many of the facades at Petra and are a reflection of the cultures that the Nabataens traded with.",
        construction2: "The facade of the Treasury features a broken pediment with a central tholos (“dome”) inside, and two obelisks appear to form into the rock of Petra at the top. Near the bottom of the Treasury we see twin Greek Gods: Pollux, Castor, and Dioscuri, who protect travelers on their journeys. \nNear the top of the Treasury, two victories are seen standing on each side of a female figure on the tholos. This female figure is believed to be the Isis-Tyche, Isis being the Egyptian Goddess and Tyche being the Greek Goddess of good fortune.",
        location1: "Petra is located in southern Jordan. It is adjacent to the mountain of Jabal Al-Madbah, in a basin surrounded by mountains forming the eastern flank of the Arabah valley running from the Dead Sea to the Gulf of Aqaba.",
        location2: "The area around Petra has been inhabited from as early as 7000 BC, and the Nabataeans might have settled in what would become the capital city of their kingdom as early as the 4th century BC.\nArchaeological work has only discovered evidence of Nabataean presence dating back to the second century BC, by which time Petra had become their capital. The Nabataeans were nomadic Arabs who invested in Petra's proximity to the incense trade routes by establishing it as a major regional trading hub.",
        quote_top: "A Rose-Red City",
        quote_bottom: "Half as Old as Time",
        quote_author: "John William Burgon",
        callout1: "They were particularly skillful in harvesting rainwater, agriculture and stone carving.",
        callout2: "Perhaps a more prominent resemblance to Hellenistic style in Petra comes with its Treasury.",
        video_caption: "“Stunning Stone Monuments of Petra | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Petra in Ma’an Governorate, Jordan.",
    },
    Editorial {
        sub_title: "The icon of Rome",
        region: "Rome, Italy",
        history1: "The Colosseum is an oval amphitheater in the center of the city of Rome, Italy. Unlike Roman theaters that were built into hillsides, the Colosseum is an entirely free-standing structure.",
        history2: "The building ceased to be used for entertainment in the early medieval era. By the late 6th century a small chapel had been built into the structure of the amphitheater, and the arena was converted into a cemetery. \nThe numerous vaulted spaces in the arcades under the seating were converted into housing and workshops, and are recorded as still being rented out as late as the 12th century.",
        construction1: "Construction began under the emperor Vespasian (r. 69-79 CE) in 72 and was completed in 80 CE under his successor and heir, Titus (r. 79-81). Further modifications were made during the reign of Domitian (r. 81-96).\nThe Colosseum is built of travertine limestone, tuff (volcanic rock), and brick-faced concrete. The outer wall is estimated to have required over 3.5 million cubic feet of travertine stone which were set without mortar; they were held together by 300 tons of iron clamps.",
        construction2: "It could hold an estimated 50,000 to 80,000 spectators at various points in its history, having an average audience of some 65,000.",
        location1: "Following the Great Fire of Rome in 64 CE, Emperor Nero seized much of the destroyed area to build his grandiose Domus Aurea (\"Golden House\"). A severe embarrassment to Nero's successors, parts of this extravagant palace and grounds, encompassing 1 sq mile, were filled with earth and built over.",
        location2: "On the site of the lake, in the middle of the palace grounds, Emperor Vespasian would build the Colosseum as part of a Roman resurgence.",
        quote_top: "Still the Largest Standing",
        quote_bottom: "Amphitheater in the World Today",
        quote_author: "",
        callout1: "It was used for gladiatorial contests and public spectacles including animal hunts, executions, reenactments of famous battles, and dramas based on Roman mythology, and mock sea battles.",
        callout2: "It is the largest ancient amphitheater ever built, and is still the largest standing amphitheater in the world today, despite its age.",
        video_caption: "“Ancient Rome 101 | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Colosseum in Rome, Italy,",
    },
    Editorial {
        sub_title: "The Great Mayan City",
        region: "Yucatan, Mexico",
        history1: "Chichen Itza was a powerful regional capital controlling north and central Yucatán. The earliest hieroglyphic date discovered at Chichen Itza is equivalent to 832 CE, while the last known date was recorded in the Osario temple in 998 CE.\nDominating the North Platform of Chichen Itza is the famous Temple of Kukulcán. The temple was identified by the first Spaniards to see it, as El Castillo (\"the castle\"), and it regularly is referred to as such.",
        history2: "The city was thought to have the most diverse population in the Maya world, a factor that could have contributed to this architectural variety.",
        construction1: "The structures of Chichen Itza were built from precisely chiseled limestone blocks that fit together perfectly without the mortar. Many of these stone buildings were originally painted in red, green, blue and purple colors depending on the availability of the pigments.\nThe stepped pyramid El Castillo stands about 98 feet (30 m) high and consists of a series of nine square terraces, each approximately 8.4 feet (2.57 m) high, with a 20 foot (6 m) high temple upon the summit.",
        construction2: "It was built upon broken terrain, which was artificially leveled to support structures such as the Castillo pyramid. Important buildings within the center were connected by a dense network of paved roads called sacbeob.",
        location1: "Chichen Itza is located in the eastern portion of Yucatán state in Mexico. Nearby, four large sinkholes, called cenotes, could have provided plentiful water year round at Chichen, making it attractive for settlement.",
        location2: "Of these cenotes, the \"Cenote Sagrado\" or Sacred Cenote, was used for the sacrifice of precious objects and human beings as a form of worship to the Maya rain god Chaac.",
        quote_top: "The Beauty Between",
        quote_bottom: "the Heavens and the Underworld",
        quote_author: "",
        callout1: "The site exhibits a multitude of architectural styles, reminiscent of styles seen in central Mexico and of the Puuc and Chenes styles of the Northern Maya lowlands.",
        callout2: "The city comprised an area of at least 1.9 sq miles (5 sq km) of densely clustered architecture.",
        video_caption: "“Ancient Maya 101 | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Chichen Itza in Yucatán State, Mexico.",
    },
    Editorial {
        sub_title: "Citadel of the Inca",
        region: "Cusco Region, Peru",
        history1: "Machu Picchu is a 15th-century Inca citadel located in the Eastern Cordillera of southern Peru on a 2,430-meter (7,970 ft) mountain ridge. Construction appears to date from two great Inca rulers, Pachacutec Inca Yupanqui (1438–1471 CE) and Túpac Inca Yupanqui (1472–1493 CE).",
        history2: "There is a consensus among archeologists that Pachacutec ordered the construction of the royal estate for his use as a retreat, most likely after a successful military campaign.\nRather it was used for 80 years before being abandoned, seemingly because of the Spanish conquests in other parts of the Inca Empire.",
        construction1: "The central buildings use the classical Inca architectural style of polished dry-stone walls of regular shape. \nInca walls have many stabilizing features: doors and windows are trapezoidal, narrowing from bottom to top; corners usually are rounded; inside corners often incline slightly into the rooms, and outside corners were often tied together by \"L\"-shaped blocks.",
        construction2: "This precision construction method made the structures at Machu Picchu resistant to seismic activity.\nThe site itself may have been intentionally built on fault lines to afford better drainage and a ready supply of fractured stone.",
        location1: "Machu Picchu is situated above a bow of the Urubamba River, which surrounds the site on three sides, where cliffs drop vertically for 1,480 feet (450 m) to the river at their base. The location of the city was a military secret, and its deep precipices and steep mountains provided natural defenses.",
        location2: "The Inca Bridge, an Inca grass rope bridge, across the Urubamba River in the Pongo de Mainique, provided a secret entrance for the Inca army. Another Inca bridge was built to the west of Machu Picchu, the tree-trunk bridge, at a location where a gap occurs in the cliff that measures 20 feet (6 m).",
        quote_top: "Few Romances Can Ever Surpass",
        quote_bottom: "That of the Granite Citadel",
        quote_author: "Hiram Bingham",
        callout1: "During its use as a royal estate, it is estimated that about 750 people lived there, with most serving as support staff who lived there permanently.",
        callout2: "The Incas were masters of this technique, called ashlar, in which blocks of stone are cut to fit together tightly without mortar.",
        video_caption: "“Machu Picchu 101 | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Machu Picchu in the Eastern Cordillera of southern Peru.",
    },
    Editorial {
        sub_title: "Heaven on Earth",
        region: "Agra, India",
        history1: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 CE by the Mughal emperor Shah Jahan (r. 1628-1658) to house the tomb of his favorite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself.",
        history2: "The tomb is the centerpiece of a 42-acre (17-hectare) complex, which include twin mosque buildings (placed symmetrically on either side of the mausoleum), a guest house, and is set in formal gardens bounded on three sides by walls.",
        construction1: "The Taj Mahal was constructed using materials from all over India and Asia. It is believed over 1,000 elephants were used to transport building materials.\nThe translucent white marble was brought from Rajasthan, the jasper from Punjab, jade and crystal from China. The turquoise was from Tibet and the lapis from Afghanistan, while the sapphire came from Sri Lanka. In all, twenty-eight types of precious and semi-precious stones were inlaid into the white marble.",
        construction2: "An area of roughly 3 acres was excavated, filled with dirt to reduce seepage, and leveled at 160 ft above riverbank. In the tomb area, wells were dug and filled with stone and rubble to form the footings of the tomb.\nThe plinth and tomb took roughly 12 years to complete. The remaining parts of the complex took an additional 10 years.",
        location1: "India's most famed building, it is situated in the eastern part of the city on the southern bank of the Yamuna River, nearly 1 mile east of the Agra Fort, also on the right bank of the Yamuna.",
        location2: "The Taj Mahal is built on a parcel of land to the south of the walled city of Agra. Shah Jahan presented Maharaja Jai Singh with a large palace in the center of Agra in exchange for the land.",
        quote_top: "Not just a Monument,",
        quote_bottom: "but a Symbol of Love.",
        quote_author: "Suman Pokhrel",
        callout1: "The Taj Mahal is distinguished as the finest example of Mughal architecture, a blend of Indian, Persian, and Islamic styles.",
        callout2: "It took the efforts of 22,000 laborers, painters, embroidery artists and stonecutters to shape the Taj Mahal.",
        video_caption: "“India’s Taj Mahal Is an Enduring Monument to Love | National Geographic.” Youtube, uploaded by National Geographic.",
        map_caption: "Map showing location of Taj Mahal in Uttar Pradesh, India.",
    },
    Editorial {
        sub_title: "A symbol of peace",
        region: "Rio de Janeiro, Brazil",
        history1: "The placement of a Christian monument on Mount Corcovado was first suggested in the mid-1850s to honor Princess Isabel, regent of Brazil and the daughter of Emperor Pedro II, but the project was not approved.\nIn 1889 the country became a republic, and owing to the separation of church and state the proposed statue was dismissed.",
        history2: "The Catholic Circle of Rio made a second proposal for a landmark statue on the mountain in 1920. The group organized an event called Semana do Monumento (\"Monument Week\") to attract donations and collect signatures to support the building of the statue. The organization was motivated by what they perceived as \"Godlessness\" in the society.\nThe designs considered for the \"Statue of the Christ\" included a representation of the Christian cross, a statue of Jesus with a globe in his hands, and a pedestal symbolizing the world.",
        construction1: "Artist Carlos Oswald and local engineer Heitor da Silva Costa designed the statue. French sculptor Paul Landowski created the work. In 1922, Landowski commissioned fellow Parisian Romanian sculptor Gheorghe Leonida, who studied sculpture at the Fine Arts Conservatory in Bucharest and in Italy.",
        construction2: "A group of engineers and technicians studied Landowski's submissions and felt building the structure of reinforced concrete instead of steel was more suitable for the cross-shaped statue. The concrete making up the base was supplied from Limhamn, Sweden. The outer layers are soapstone, chosen for its enduring qualities and ease of use.",
        location1: "Corcovado, which means \"hunchback\" in Portuguese, is a mountain in central Rio de Janeiro, Brazil. It is a 2,329 foot (710 m) granite peak located in the Tijuca Forest, a national park.",
        location2: "Corcovado hill lies just west of the city center but is wholly within the city limits and visible from great distances.",
        quote_top: "A Perfect Union Between",
        quote_bottom: "Nature and Architecture",
        quote_author: "",
        callout1: "The statue of Christ the Redeemer with open arms, a symbol of peace, was chosen.",
        callout2: "Construction took nine years, from 1922 to 1931, and cost the equivalent of US$250,000 (equivalent to $3,600,000 in 2020) and the monument opened on October 12, 1931.",
        video_caption: "“The Majestic Statue of Christ the Redeemer - Seven Wonders of the Modern World - See U in History.” Youtube, uploaded by See U in History / Mythology.",
        map_caption: "Map showing location of Christ the Redeemer in Rio de Janeiro, Brazil.",
    },
];
