//! Host-side tooling for a Splash-OH app.
//!
//! Runs on the developer's machine, not the phone. That is why it is a separate
//! crate: everything else here builds only for `aarch64-unknown-linux-ohos`, so
//! nothing else in this workspace can be `cargo run`.
//!
//! ```text
//! splash-oh shim [path]     write the bridge shim where a dev server can serve it
//! splash-oh new <dir>       start a project
//! splash-oh dev             print what to run for a live-reload loop
//! ```

use std::path::{Path, PathBuf};

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let cmd = args.first().map(String::as_str).unwrap_or("help");
    let rest = &args[args.len().min(1)..];

    let code = match cmd {
        "shim" => shim(rest),
        "new" => new_project(rest),
        "dev" => dev(rest),
        "help" | "--help" | "-h" => {
            usage();
            0
        }
        other => {
            eprintln!("splash-oh: unknown command {other:?}\n");
            usage();
            2
        }
    };
    std::process::exit(code);
}

fn usage() {
    println!(
        "\
splash-oh — tooling for a Splash-OH app

  splash-oh new <dir>        create a project: a frontend, a plugin crate, a config
  splash-oh shim [path]      write the bridge shim (default: public/__splash.js)
  splash-oh dev              open the USB tunnel for a live-reload loop

A frontend must load the shim before it can call native code:

  <script src=\"/__splash.js\"></script>

In a release build the app serves that itself. A dev server does not know about
it, which is what `splash-oh shim` is for — write it into the static directory
your bundler serves, and the same tag works in both."
    );
}

/// Write the shim where a dev server will serve it.
fn shim(args: &[String]) -> i32 {
    let path = args
        .first()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("public/__splash.js"));

    if let Some(dir) = path.parent() {
        if !dir.as_os_str().is_empty() {
            if let Err(e) = std::fs::create_dir_all(dir) {
                eprintln!("splash-oh: cannot create {}: {e}", dir.display());
                return 1;
            }
        }
    }
    // A header, because this file lands in someone's source tree and the next
    // person to see it should not have to guess whether it is theirs to edit.
    let body = format!(
        "// Generated by `splash-oh shim`. Do not edit; regenerate after upgrading.\n\
         // Served by the app itself in a release build — this copy exists so a\n\
         // dev server can answer the same URL.\n{}\n",
        splash_oh_core::SHIM_JS
    );
    match std::fs::write(&path, body) {
        Ok(()) => {
            println!("wrote {}", path.display());
            0
        }
        Err(e) => {
            eprintln!("splash-oh: cannot write {}: {e}", path.display());
            1
        }
    }
}

fn dev(args: &[String]) -> i32 {
    let port = args
        .iter()
        .find_map(|a| a.strip_prefix("--port="))
        .unwrap_or("5173")
        .to_string();

    // Over USB, not over Wi-Fi.
    //
    // The obvious route is to point the phone at your machine's LAN address,
    // and on this hardware that failed: the phone and the Mac shared a
    // 192.168.125.x subnet over the USB link, and a request from the phone
    // still came back ERR_ADDRESS_UNREACHABLE. `hdc rport` sidesteps the
    // question -- it tunnels a device port to a host port over the debug
    // connection, so the phone connects to its own 127.0.0.1 and there is no
    // network to configure or firewall to open.
    let forward = format!("tcp:{port}");
    let status = std::process::Command::new("hdc")
        .args(["rport", &forward, &forward])
        .output();
    match status {
        Ok(o) if String::from_utf8_lossy(&o.stdout).contains("OK") => {
            println!("tunnelled device 127.0.0.1:{port} -> this machine's :{port}");
        }
        Ok(o) => {
            let out = String::from_utf8_lossy(&o.stdout);
            let e = String::from_utf8_lossy(&o.stderr);
            eprintln!(
                "splash-oh: hdc rport did not confirm: {}{}",
                out.trim(),
                e.trim()
            );
            eprintln!("           is a device connected? `hdc list targets`");
        }
        Err(e) => {
            eprintln!("splash-oh: could not run hdc: {e}");
            eprintln!("           put the OpenHarmony toolchains directory on PATH.");
        }
    }

    println!(
        "\n\
Now, in two terminals:

  npm run dev
  SPLASH_DEV_SERVER=http://127.0.0.1:{port} ./build.sh

Frontend edits reload on the device. Rust edits still need a rebuild.

The tunnel does not survive a replug or a reboot of the phone — rerun
`splash-oh dev` if the page stops loading.

Copying files onto the phone instead is not an option: hdc's push resolves
outside the app's sandbox, so they never arrive where the app can read them.
Hence a server."
    );
    0
}

fn new_project(args: &[String]) -> i32 {
    let Some(dir) = args.first() else {
        eprintln!("splash-oh new <dir>");
        return 2;
    };
    let root = Path::new(dir);
    if root.exists() {
        eprintln!("splash-oh: {} already exists", root.display());
        return 1;
    }
    match scaffold(root) {
        Ok(()) => {
            println!(
                "\
Created {}

  cd {}
  npm install
  npm run build
  splash-oh shim
  SPLASH_FRONTEND_DIR=$PWD/dist ./build.sh

Edit splash.toml to change the app's name, id and icon.",
                root.display(),
                root.display()
            );
            0
        }
        Err(e) => {
            eprintln!("splash-oh: {e}");
            1
        }
    }
}

fn scaffold(root: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(root.join("src"))?;
    std::fs::create_dir_all(root.join("public"))?;
    std::fs::create_dir_all(root.join("plugin/src"))?;

    std::fs::write(
        root.join("splash.toml"),
        include_str!("template/splash.toml"),
    )?;
    std::fs::write(root.join("index.html"), include_str!("template/index.html"))?;
    std::fs::write(
        root.join("package.json"),
        include_str!("template/package.json"),
    )?;
    std::fs::write(root.join("src/main.js"), include_str!("template/main.js"))?;
    std::fs::write(
        root.join("src/style.css"),
        include_str!("template/style.css"),
    )?;
    std::fs::write(
        root.join("plugin/Cargo.toml"),
        include_str!("template/plugin-Cargo.toml"),
    )?;
    std::fs::write(
        root.join("plugin/src/lib.rs"),
        include_str!("template/plugin-lib.rs"),
    )?;
    std::fs::write(root.join("README.md"), include_str!("template/README.md"))?;
    std::fs::write(
        root.join("public/__splash.js"),
        format!(
            "// Generated by `splash-oh new`. Regenerate with `splash-oh shim`.\n{}\n",
            splash_oh_core::SHIM_JS
        ),
    )?;
    Ok(())
}
