//! Search suggestions, from each wonder's `search/*_search_data.dart`.
//!
//! Wonderous offers these as chips on the artifact search screen and queries
//! the Met with whatever is chosen. The chips are the app's own words; the
//! query is answered here from the artifacts that ship, since the search screen
//! without a network is otherwise a text field that does nothing.

const PYRAMIDS_SUGGEST: &[&str] = &[
    "maatkare",
    "cylinder",
    "seal",
    "iii",
    "shabti",
    "alloy",
    "travertine",
    "faience",
    "jasper",
    "abumeh",
    "seneb",
    "impressed",
    "stela",
    "clay",
    "khasekhemwy",
    "abu",
    "royal",
    "glass",
    "fragment",
    "bronzes",
    "relief",
    "red",
    "bronze",
    "steatite",
];

const GREAT_WALL_OF_CHINA_SUGGEST: &[&str] = &[
    "longquan",
    "bodhisattva",
    "horn",
    "figure",
    "mirror",
    "mythical",
    "jingdezhen",
    "figures",
    "model",
    "birds",
    "mirrors",
    "sample",
    "stand",
    "copper",
    "tomb",
    "architectural",
    "celadon",
    "alloy",
    "silver",
    "ware",
    "colored",
    "incense",
    "sculpture",
    "earthenware",
];

const PETRA_SUGGEST: &[&str] = &[
    "stamp",
    "figure",
    "cylinder",
    "membranophone",
    "seal",
    "copper",
    "molded",
    "brass",
    "dagger",
    "alloy",
    "silver",
    "slip",
    "animal",
    "stone",
    "opaque",
    "sculpture",
    "earthenware",
    "incised",
    "ink",
    "jambiya",
    "paper",
    "ceramics",
    "jasper",
    "metal",
];

const COLOSSEUM_SUGGEST: &[&str] = &[
    "marble",
    "wall",
    "mosaic",
    "ornament",
    "miscellaneous",
    "pentelic",
    "grotesque",
    "denarius",
    "amphora",
    "handle",
    "silver",
    "terracotta",
    "stone",
    "sculpture",
    "phallic",
    "urn",
    "cinerary",
    "vase",
    "beaker",
    "ivory",
    "fresco",
    "glass",
    "cup",
    "shape",
];

const CHICHEN_ITZA_SUGGEST: &[&str] = &[
    "stamp",
    "yoke",
    "hacha",
    "god",
    "male",
    "female",
    "serpentine",
    "figure",
    "andesite",
    "cylindrical",
    "chisel",
    "earflare",
    "cinnabar",
    "relief",
    "model",
    "plate",
    "ornament",
    "red",
    "censer",
    "jade",
    "slip",
    "gold",
    "implements",
    "musical",
];

const MACHU_PICCHU_SUGGEST: &[&str] = &[
    "hat",
    "figure",
    "earflare",
    "prosopis",
    "fiber",
    "ornament",
    "paccha",
    "copper",
    "feline",
    "bronze",
    "canopa",
    "costumes",
    "dish",
    "tomb",
    "lime",
    "miniature",
    "top",
    "wood",
    "bottle",
    "gilded",
    "inlay",
    "tumi",
    "alloy",
    "silver",
];

const TAJ_MAHAL_SUGGEST: &[&str] = &[
    "shrine",
    "dagger",
    "alloy",
    "stone",
    "sculpture",
    "ink",
    "paper",
    "album",
    "leather",
    "katar",
    "folio",
    "textiles",
    "sandstone",
    "fragment",
    "semiprecious",
    "coins",
    "illustrated",
    "relief",
    "red",
    "silk",
    "bronze",
    "jade",
    "black",
    "wood",
];

const CHRIST_THE_REDEEMER_SUGGEST: &[&str] = &[
    "ivory",
    "blown",
    "cane",
    "hole",
    "vibrated",
    "aerophone",
    "blow",
    "fan",
    "flute",
    "bamboo",
    "lip",
];

/// Same order as `WONDERS`.
pub const SUGGESTIONS: &[&[&str]] = &[
    PYRAMIDS_SUGGEST,
    GREAT_WALL_OF_CHINA_SUGGEST,
    PETRA_SUGGEST,
    COLOSSEUM_SUGGEST,
    CHICHEN_ITZA_SUGGEST,
    MACHU_PICCHU_SUGGEST,
    TAJ_MAHAL_SUGGEST,
    CHRIST_THE_REDEEMER_SUGGEST,
];
