//! Splash DSL → native ArkUI widgets.
//!
//! This is the piece that makes the repo's claim true: the widget tree is not
//! written in Rust, it is **evaluated by the Splash VM** (`makepad-script`) at
//! runtime and then walked into ArkUI nodes. The VM is renderer-free — it has
//! no dependency on makepad-platform, makepad-draw or any widget crate — so
//! nothing about makepad's renderer comes along for the ride.
//!
//! ## The tree the DSL produces
//!
//! A node is a plain object with a `t` type tag, optional attributes, and an
//! optional `c` array of children:
//!
//! ```text
//! {t: "column", bg: 0xFFF2F2F7, c: [
//!     {t: "text", text: "Components", size: 28, weight: 7},
//!     {t: "button", label: "Tap me", h: 44},
//! ]}
//! ```
//!
//! Deliberately plain data rather than makepad's `Button{...}` component
//! syntax: that syntax resolves through makepad's *widget registry*, which is
//! exactly the coupling this repo exists to avoid. Everything that makes the
//! DSL worth having is still available above this layer — variables, `fn`,
//! loops, conditionals, string building — because a real VM evaluates it. The
//! catalog leans on that heavily (see `assets/catalog.splash`).

use crate::arkui::{attr, event, ty, Node};
// The VM comes from ymote/Splash, which re-exports it as `vm` from its own
// pinned vendored copy. Importing it under the old name keeps the walk below
// unchanged; what changes is provenance, not API.
use splash_core::vm as makepad_script;

use makepad_script::apply::*;
use makepad_script::array::ScriptArrayStorage;
use makepad_script::makepad_live_id::*;
use makepad_script::traits::*;
use makepad_script::*;

/// Evaluate the catalog for a given screen.
///
/// `screen` and `bench` are bound as ordinary `let`s prepended to the source —
/// the simplest way to pass host state into a script without a scope object.
// The two DSL programs live with their examples. The evaluator entry points
// stay here because `app.rs` dispatches flutter routes through the interning
// in this module; moving them out needs the same hook inversion `set_router`
// uses, which is a change of its own.
pub fn build_screen(screen: &str, bench: Option<&str>) -> Option<Node> {
    const CATALOG: &str = include_str!("../../../examples/material-catalog/assets/catalog.splash");
    let esc = |s: &str| {
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    };
    // `text_lines` in the DSL estimates wrapped height from `s.len()`, which
    // cannot see embedded newlines — the benchmark report has plenty, and it
    // overflowed its card. Rust can just count them properly and pass the
    // answer down.
    let report = bench.unwrap_or("");
    let src = format!(
        "let screen = \"{}\"\nlet bench = \"{}\"\nlet bench_lines = {}\n{}",
        esc(screen),
        esc(report),
        display_lines(report, BENCH_CHARS_PER_LINE),
        CATALOG
    );
    build(&src)
}

/// The component ids `catalog.splash` lists, in the order it lists them.
///
/// Generated by `build.rs` from the DSL itself, so the two cannot disagree —
/// see the note there for why this is generated rather than tested.

/// Tap id the DSL uses for "open the screen at this index".
pub const CATALOG_NAV_BASE: i32 = 1000;
/// Tap id for the back button on a screen.
pub const CATALOG_NAV_BACK: i32 = 999;

/// Roughly how many characters fit on one line of the report, at the size and
/// width `catalog.splash` renders it. Matches the DSL's own 2.2 chars/vp rule.
const BENCH_CHARS_PER_LINE: usize = 63;

/// Wrapped line count, counting hard newlines as well as wrapping.
fn display_lines(s: &str, per_line: usize) -> usize {
    s.lines()
        .map(|l| {
            if l.is_empty() {
                1
            } else {
                l.len().div_ceil(per_line)
            }
        })
        .sum::<usize>()
        .max(1)
}

/// The flutter/samples kit, rendered to native ArkUI.
///
/// Same `.splash` source the makepad backend renders — vendored from
/// Splash-Makepad's `components/flutter/` by its `assemble` example. That the
/// identical kit drives two unrelated native toolkits is the whole point of the
/// UiNode split; this is the ArkUI half of it.
///
/// `route` picks the screen, `dark` the palette, exactly as the makepad host
/// injects them.
pub fn build_flutter(route: &str, dark: bool) -> Option<Node> {
    const KIT: &str = include_str!("../../../examples/flutter-catalog/assets/flutter.splash");
    FLUTTER_ROUTES.with(|r| r.borrow_mut().clear());
    BUILT_ROUTE.with(|b| *b.borrow_mut() = route.to_string());
    let src = format!(
        "let st = {{ route: {route:?}, dark: {}, t: {}, backend: \"arkui\" }}\n{KIT}",
        u8::from(dark),
        elapsed_secs()
    );
    build(&src)
}

/// Tap ids for the flutter kit start here. The kit names its targets with
/// route *strings* (`tapto: "date_planner/maya"`), but ArkUI events carry an
/// i32, so the walk interns each route as it meets it and hands back an index.
pub const FLUTTER_NAV_BASE: i32 = 2000;

/// Seconds since the first mount, handed to the kit as `st.t`.
///
/// The DSL evaluates a tree once per mount and has no tween or controller, so
/// the only thing that can make a screen move is re-mounting it against a
/// changing clock. `anim_tick()` drives that from ArkTS.
fn elapsed_secs() -> f64 {
    use std::sync::OnceLock;
    use std::time::Instant;
    static START: OnceLock<Instant> = OnceLock::new();
    START.get_or_init(Instant::now).elapsed().as_secs_f64()
}

thread_local! {
    /// Nodes that declared a `drift`, with where and how long. Filled while the
    /// tree is walked, drained by the host once it is mounted.
    static DRIFTS: std::cell::RefCell<Vec<(crate::arkui::NodeHandle, f32, f32, i32)>> =
        const { std::cell::RefCell::new(Vec::new()) };
    static FLUTTER_ROUTES: std::cell::RefCell<Vec<String>> =
        const { std::cell::RefCell::new(Vec::new()) };
    /// The first `scroll` node of the tree currently mounted.
    ///
    /// A tap rebuilds everything, so this is the handle whose offset has to be
    /// read before the old tree is dropped and written back onto the new one —
    /// otherwise checking a checkbox halfway down a screen leaves you at the
    /// top of it. First, not all: every screen in this kit is one scrolling
    /// column under an app bar, and a wrong guess here scrolls the wrong thing
    /// rather than failing loudly.
    static SCROLL_NODE: std::cell::Cell<crate::arkui::NodeHandle> =
        const { std::cell::Cell::new(std::ptr::null_mut()) };
    static BUILT_ROUTE: std::cell::RefCell<String> =
        const { std::cell::RefCell::new(String::new()) };
}

/// The route the mounted tree was built for.
///
/// Recorded here rather than by the caller because there are three ways a tree
/// gets mounted — `rebuild`, `goBack` and `catalogScreen` — and only the first
/// went through the place that used to track this. The other two left it stale,
/// so a later tap could compare against the wrong route and restore a scroll
/// offset captured on a different screen.
pub fn built_route() -> String {
    BUILT_ROUTE.with(|b| b.borrow().clone())
}

/// The mounted tree's scrolling node, if it has one.
pub fn scroll_node() -> crate::arkui::NodeHandle {
    SCROLL_NODE.with(|s| s.get())
}

fn note_scroll_node(h: crate::arkui::NodeHandle) {
    SCROLL_NODE.with(|s| {
        if s.get().is_null() {
            s.set(h);
        }
    });
}

/// Intern a route string, returning the tap id that stands for it.
fn intern_route(route: &str) -> i32 {
    FLUTTER_ROUTES.with(|r| {
        let mut v = r.borrow_mut();
        match v.iter().position(|s| s == route) {
            Some(i) => FLUTTER_NAV_BASE + i as i32,
            None => {
                v.push(route.to_string());
                FLUTTER_NAV_BASE + (v.len() - 1) as i32
            }
        }
    })
}

/// The route a tap id stands for, or `None` if it is not one of ours.
pub fn flutter_route(id: i32) -> Option<String> {
    if id < FLUTTER_NAV_BASE {
        return None;
    }
    FLUTTER_ROUTES.with(|r| r.borrow().get((id - FLUTTER_NAV_BASE) as usize).cloned())
}

/// Evaluate the LLM-generated weather card (`assets/weather.splash`) → native
/// ArkUI tree. Self-contained (data inlined), so it needs no bound host vars.
pub fn build_weather() -> Option<Node> {
    const WEATHER: &str = include_str!("../assets/weather.splash");
    build(WEATHER)
}

/// Evaluate the card lowered from a SEMANTIC PLAN by expand_oh.py — the same
/// plan that expand.py lowers to makepad Splash DSL. Additive: exists purely to
/// test whether one backend-agnostic plan can drive two renderers.
pub fn build_planweather() -> Option<Node> {
    const PLANWEATHER: &str = include_str!("../assets/planweather.splash");
    build(PLANWEATHER)
}

/// The YouTube app's native chrome bar. The video content is an ArkTS `Web`
/// component (see pages/Index.ets) — OpenHarmony's WebView cannot live in the
/// native ArkUI node tree, so Splash-OH renders the app shell and the Web sits
/// below it.
pub fn build_youtube() -> Option<Node> {
    const YOUTUBE: &str = include_str!("../assets/youtube.splash");
    build(YOUTUBE)
}

/// Evaluate Splash source and build the native tree it describes.
/// Start every drift the last build declared.
///
/// Called after the tree is mounted, because `animate` reads its UI context
/// from a live node. Each drift is one long native animation; re-calling this
/// on a slow timer restarts them, and ArkUI does the interpolation in between
/// at the display's rate rather than the timer's.
///
/// # Safety
/// Must be called only while the tree those handles came from is mounted.
pub unsafe fn start_drifts() -> usize {
    let drifts: Vec<(crate::arkui::NodeHandle, f32, f32, i32)> =
        DRIFTS.with(|d| d.borrow().clone());
    let n = drifts.len();
    for (h, dx, dy, ms) in drifts {
        // Back to the start with no animation, then out to the far side with
        // one. A cloud that only ever eased toward its target would stall
        // there; this is what makes the motion continuous.
        crate::arkui::Node::set_translate(h, 0.0, 0.0);
        crate::arkui::animate(h, ms, crate::arkui::CURVE_LINEAR, move || {
            crate::arkui::Node::set_translate(h, dx, dy);
        });
    }
    n
}

/// How many drifts the last build declared.
pub fn drift_count() -> usize {
    DRIFTS.with(|d| d.borrow().len())
}

/// Forget the drifts from a previous build.
pub fn clear_drifts() {
    DRIFTS.with(|d| d.borrow_mut().clear());
}

pub fn build(src: &str) -> Option<Node> {
    let mut std_slot = 0;
    let mut host = 0;
    let vm = &mut ScriptVm {
        host: &mut host,
        std: &mut std_slot,
        bx: Box::new(ScriptVmBase::new()),
    };

    // Slots are declared during the walk below, so last build's have to go
    // first — otherwise every web surface ever declared stays on screen.
    crate::web_reset();
    SCROLL_NODE.with(|s| s.set(std::ptr::null_mut()));

    // Give the DSL its network capability, so the card fetches its own data.
    register_net_capabilities(vm);
    register_host_capabilities(vm);

    let value = vm.eval(ScriptMod {
        cargo_manifest_path: String::new(),
        module_path: String::from("splash_oh"),
        file: String::from("catalog.splash"),
        line: 0,
        column: 0,
        code: src.to_string(),
        values: Vec::new(),
    });

    if value.is_nil() {
        // "evaluated to nil" on its own is the least useful error this codebase
        // produces -- it covers a parse error, a runtime error and a script that
        // legitimately returned nothing. splash-core can tell them apart, so ask.
        match splash_core::check_syntax(src) {
            Ok(report) if !report.diagnostics.is_empty() => {
                for d in report.diagnostics.iter().take(4) {
                    crate::log(&format!("dsl: syntax: {d:?}"));
                }
            }
            Ok(_) => crate::log(
                "dsl: script parsed but evaluated to nil (runtime error, or it returned nothing)",
            ),
            Err(e) => crate::log(&format!("dsl: syntax check failed: {e:?}")),
        }
        return None;
    }
    walk(vm, value, 0, "")
}

/// Expose the network capability to the DSL as injected global functions, so
/// the weather card fetches its own live data instead of shipping a snapshot.
/// Responses are cached by URL (see `net`), so the ~30 field reads the card
/// does are two HTTP requests: one for weather, one for air quality.
fn register_net_capabilities(vm: &mut ScriptVm) {
    // `fetch_num(url, path, i)` -> the number at a dotted JSON path (i>=0 adds
    // one array index, for the per-day forecast). nil when missing.
    let f_num = add_global_fn(
        vm,
        &[
            (id!(url), ScriptValue::NIL),
            (id!(path), ScriptValue::NIL),
            (id!(i), ScriptValue::NIL),
        ],
        |vm, a| {
            let url = string_prop(vm, a, id!(url)).unwrap_or_default();
            let path = string_prop(vm, a, id!(path)).unwrap_or_default();
            let i = num_prop(vm, a, id!(i)).unwrap_or(-1.0) as i32;
            match crate::net::fetch_num(&url, &path, i) {
                Some(n) => ScriptValue::from_f64(n),
                None => ScriptValue::NIL,
            }
        },
    );
    vm.set_injected_global(id!(fetch_num), f_num);

    // `fetch_fmt(url, path, i, suffix)` -> the number rounded + suffixed, e.g.
    // "22°", "89%", "10 µg/m³".
    let f_fmt = add_global_fn(
        vm,
        &[
            (id!(url), ScriptValue::NIL),
            (id!(path), ScriptValue::NIL),
            (id!(i), ScriptValue::NIL),
            (id!(suffix), ScriptValue::NIL),
        ],
        |vm, a| {
            let url = string_prop(vm, a, id!(url)).unwrap_or_default();
            let path = string_prop(vm, a, id!(path)).unwrap_or_default();
            let i = num_prop(vm, a, id!(i)).unwrap_or(-1.0) as i32;
            let suffix = string_prop(vm, a, id!(suffix)).unwrap_or_default();
            let s = crate::net::fetch_fmt(&url, &path, i, &suffix);
            vm.bx.heap.new_string_from_str(&s)
        },
    );
    vm.set_injected_global(id!(fetch_fmt), f_fmt);

    // `fetch_weekday(url, path, i)` -> "Tue" for the ISO date at that path.
    let f_wd = add_global_fn(
        vm,
        &[
            (id!(url), ScriptValue::NIL),
            (id!(path), ScriptValue::NIL),
            (id!(i), ScriptValue::NIL),
        ],
        |vm, a| {
            let url = string_prop(vm, a, id!(url)).unwrap_or_default();
            let path = string_prop(vm, a, id!(path)).unwrap_or_default();
            let i = num_prop(vm, a, id!(i)).unwrap_or(-1.0) as i32;
            let s = crate::net::fetch_weekday(&url, &path, i).unwrap_or_else(|| "--".to_string());
            vm.bx.heap.new_string_from_str(&s)
        },
    );
    vm.set_injected_global(id!(fetch_weekday), f_wd);

    // ---- capability parity with the makepad host --------------------------
    //
    // The portability test lowered one semantic plan to both backends and found
    // the real porting cost is HOST CAPABILITY, not widgets: makepad exposes
    // thirty-odd sys.* helpers and this backend had five, so a plan's SunMoon
    // section could not render here at all. These four close that gap; each
    // mirrors its sys.* counterpart's semantics exactly.

    // `moonphase(field)` -> "Full Moon" | "满月" | "87" | "0.51". Clock-only, so
    // it never shows a placeholder. field: name | name_zh | illumination | phase.
    let f_moon = add_global_fn(vm, &[(id!(field), ScriptValue::NIL)], |vm, a| {
        let field = string_prop(vm, a, id!(field)).unwrap_or_default();
        let s = crate::net::moonphase(&field);
        vm.bx.heap.new_string_from_str(&s)
    });
    vm.set_injected_global(id!(moonphase), f_moon);

    // Numeric form, for arithmetic or a shader uniform.
    let f_moonnum = add_global_fn(vm, &[(id!(field), ScriptValue::NIL)], |vm, a| {
        let field = string_prop(vm, a, id!(field)).unwrap_or_default();
        ScriptValue::from_f64(crate::net::moonnum(&field))
    });
    vm.set_injected_global(id!(moonnum), f_moonnum);

    // `daylight(url)` -> 0 at sunrise, 1 at sunset; outside that range it is
    // night. Needs a forecast url carrying daily=sunrise,sunset & timezone=auto.
    let f_day = add_global_fn(vm, &[(id!(url), ScriptValue::NIL)], |vm, a| {
        let url = string_prop(vm, a, id!(url)).unwrap_or_default();
        ScriptValue::from_f64(crate::net::daylight(&url))
    });
    vm.set_injected_global(id!(daylight), f_day);

    // `weekmin(url, path)` / `weekmax(url, path)` -> the extent of a 7-element
    // daily array. A card cannot know this: the values are a live fetch, so a
    // model asked for the week's range guesses at numbers it has never seen.
    let f_wmin = add_global_fn(
        vm,
        &[(id!(url), ScriptValue::NIL), (id!(path), ScriptValue::NIL)],
        |vm, a| {
            let url = string_prop(vm, a, id!(url)).unwrap_or_default();
            let path = string_prop(vm, a, id!(path)).unwrap_or_default();
            ScriptValue::from_f64(crate::net::week_extent(&url, &path, false).unwrap_or(0.0))
        },
    );
    vm.set_injected_global(id!(weekmin), f_wmin);

    let f_wmax = add_global_fn(
        vm,
        &[(id!(url), ScriptValue::NIL), (id!(path), ScriptValue::NIL)],
        |vm, a| {
            let url = string_prop(vm, a, id!(url)).unwrap_or_default();
            let path = string_prop(vm, a, id!(path)).unwrap_or_default();
            ScriptValue::from_f64(crate::net::week_extent(&url, &path, true).unwrap_or(30.0))
        },
    );
    vm.set_injected_global(id!(weekmax), f_wmax);

    // `geocode(name, field)` / `geocodenum(name, field)` -> facts about a place
    // NAME, so a card never carries a coordinate a model recalled. The lookup
    // language follows the script of the query: open-meteo indexes per language,
    // and "上海" with language=en returns nothing.
    let f_geo = add_global_fn(
        vm,
        &[
            (id!(name), ScriptValue::NIL),
            (id!(field), ScriptValue::NIL),
        ],
        |vm, a| {
            let name = string_prop(vm, a, id!(name)).unwrap_or_default();
            let field = string_prop(vm, a, id!(field)).unwrap_or_default();
            let s = crate::net::geocode(&name, &field).unwrap_or_else(|| "--".to_string());
            vm.bx.heap.new_string_from_str(&s)
        },
    );
    vm.set_injected_global(id!(geocode), f_geo);

    let f_geonum = add_global_fn(
        vm,
        &[
            (id!(name), ScriptValue::NIL),
            (id!(field), ScriptValue::NIL),
        ],
        |vm, a| {
            let name = string_prop(vm, a, id!(name)).unwrap_or_default();
            let field = string_prop(vm, a, id!(field)).unwrap_or_default();
            ScriptValue::from_f64(crate::net::geocodenum(&name, &field))
        },
    );
    vm.set_injected_global(id!(geocodenum), f_geonum);
}

/// Expose the device capabilities to the DSL as a single `invoke(tool)` global.
///
/// This is the thing `platform_channels` demonstrates: a UI calling into the
/// platform and getting a typed answer back. Flutter spells it MethodChannel;
/// here the script asks the host by name and the host answers, which is the
/// same contract with a different spelling. The bridge already carries ~45 of
/// these for web pages (`splash.invoke`); this hands the same registry to the
/// DSL.
///
/// A tool that does not exist answers with a marker rather than failing, so a
/// screen can render on a backend that has no capabilities at all.
fn register_host_capabilities(vm: &mut ScriptVm) {
    let f = add_global_fn(vm, &[(id!(tool), ScriptValue::NIL)], |vm, a| {
        let tool = string_prop(vm, a, id!(tool)).unwrap_or_default();
        let out = crate::host_invoke(&tool);
        vm.bx.heap.new_string_from_str(&out)
    });
    vm.set_injected_global(id!(invoke), f);

    // The other half of an interactive screen: read what a tap wrote.
    //
    // A function rather than an object injected into `st`. A missing key on an
    // object reads as nil, and nil then flows into an argb() or a width and
    // surfaces somewhere else entirely as a blank box — so the default belongs
    // where the lookup happens.
    let g = add_global_fn(
        vm,
        &[(id!(key), ScriptValue::NIL), (id!(dflt), ScriptValue::NIL)],
        |vm, a| {
            let key = string_prop(vm, a, id!(key)).unwrap_or_default();
            let dflt = num_prop(vm, a, id!(dflt)).unwrap_or(0.0);
            ScriptValue::from_f64(crate::state::get_or_seed(&key, dflt))
        },
    );
    vm.set_injected_global(id!(sget), g);
}

/// Register a native function on the VM and return it as a value ready to inject
/// as a global. The closure receives the call's argument object as a value.
fn add_global_fn<F>(vm: &mut ScriptVm, args: &[(LiveId, ScriptValue)], f: F) -> ScriptValue
where
    F: Fn(&mut ScriptVm, ScriptValue) -> ScriptValue + 'static,
{
    let base = &mut *vm.bx;
    let mut native = base.code.native.borrow_mut();
    let obj = native.add_fn(&mut base.heap, args, move |vm, args| f(vm, args.into()));
    obj.into()
}

/// One DSL object → one ArkUI node, recursing into `c`.
fn walk(vm: &mut ScriptVm, value: ScriptValue, depth: usize, parent: &str) -> Option<Node> {
    // A malformed script should not be able to blow the native stack.
    if depth > 32 {
        return None;
    }
    let tag = string_prop(vm, value, id!(t)).unwrap_or_default();
    let node_ty = match tag.as_str() {
        "column" => ty::column(),
        "timepicker" => ty::timepicker(),
        "textpicker" => ty::textpicker(),
        "swiper" => ty::swiper(),
        "grid" => ty::grid(),
        "waterflow" => ty::waterflow(),
        "refresh" => ty::refresh(),
        "list" => ty::list(),
        "row" => ty::row(),
        "stack" => ty::stack(),
        "scroll" => ty::scroll(),
        "text" => ty::text(),
        "button" => ty::button(),
        "toggle" => ty::toggle(),
        "checkbox" => ty::checkbox(),
        "radio" => ty::radio(),
        "slider" => ty::slider(),
        "progress" => ty::progress(),
        "loading" => ty::loading(),
        "input" => ty::input(),
        "textarea" => ty::textarea(),
        "datepicker" => ty::datepicker(),
        "image" => ty::image(),
        // A web surface: reserve the space here, and tell the host to put a
        // real WebView at these coordinates. Same mechanism the bridge's own
        // cards use; this reaches it from the DSL.
        //
        // `src`/`x`/`y`/`w` on this node are the *slot's* geometry in device
        // pixels, not the spacer's. They must not reach the generic attribute
        // pass below: `w: 1320` there means 1320vp, about 4300px, and ArkUI
        // dies inside SetWidth rather than clamping. That crash took the whole
        // app down on a screen the index marked done. `h` is the one dimension
        // that means the same thing to both, so it is left to fall through.
        "web" => {
            let src = string_prop(vm, value, id!(src)).unwrap_or_default();
            let x = num_prop(vm, value, id!(x)).unwrap_or(0.0) as f32;
            let y = num_prop(vm, value, id!(y)).unwrap_or(0.0) as f32;
            let w = num_prop(vm, value, id!(w)).unwrap_or(0.0) as f32;
            let h = num_prop(vm, value, id!(h)).unwrap_or(0.0) as f32;
            crate::web_declare(&src, x, y, w, h);
            ty::column()
        }
        other => {
            crate::log(&format!("dsl: unknown node type {other:?}"));
            return None;
        }
    };

    let mut node = Node::new(node_ty)?;
    if tag == "scroll" {
        note_scroll_node(node.raw());
    }

    // See the "web" arm: this node's `src`/`x`/`y`/`w` describe the WebView the
    // host will composite, not the spacer standing in for it here.
    let slot_geometry = tag == "web";

    // --- attributes -------------------------------------------------------
    if let Some(s) = string_prop(vm, value, id!(text)) {
        node = node.text(&s);
    }
    if let Some(s) = string_prop(vm, value, id!(label)) {
        node = node.label(&s);
    }
    if let Some(s) = string_prop(vm, value, id!(placeholder)) {
        node = node.string_attr(attr::input_placeholder(), &s);
    }
    // `src`/`fit` are what make an image node actually show pixels: a rawfile
    // resource ref (`resource://RAWFILE/...`) and an ArkUI ObjectFit. Without
    // these the DSL could name an `image` node but never give it a source, so
    // it rendered blank — which is exactly why the LLM card showed no images.
    if let Some(s) = string_prop(vm, value, id!(src)) {
        if !slot_geometry {
            node = node.string_attr(attr::image_src(), &s);
        }
    }
    if let Some(v) = num_prop(vm, value, id!(fit)) {
        node = node.i32_attr(attr::image_fit(), v as i32);
    }
    // `range: "A;B;C"` populates a text picker. A picker with no range is not
    // an error — it draws, and draws its rows empty, which is how the catalog
    // screen shipped looking broken.
    if let Some(s) = string_prop(vm, value, id!(range)) {
        // 0 is ARKUI_TEXTPICKER_RANGETYPE_SINGLE: one column, items split on ';'.
        node = node.i32_string_attr(attr::textpicker_range(), 0, &s);
    }
    // `talign: n` is ArkUI_TextAlignment — 1 is CENTER. Distinct from `align`,
    // which positions a container's children rather than glyphs within a text.
    if let Some(v) = num_prop(vm, value, id!(talign)) {
        node = node.i32_attr(attr::text_align(), v as i32);
    }
    if let Some(v) = num_prop(vm, value, id!(w)) {
        if !slot_geometry {
            node = node.width(v as f32);
        }
    }
    if let Some(v) = num_prop(vm, value, id!(h)) {
        node = node.height(v as f32);
    }
    if let Some(v) = num_prop(vm, value, id!(size)) {
        node = node.font_size(v as f32);
    }
    if let Some(v) = num_prop(vm, value, id!(weight)) {
        node = node.font_weight(v as i32);
    }
    // A named font family. Without this the DSL could only ever render in the
    // system face, which is enough for a component catalog and not enough for
    // an app whose identity is its typography -- Wonderous is three faces and
    // reads wrong in any of them.
    if let Some(v) = string_prop(vm, value, id!(font)) {
        if !v.is_empty() {
            node = node.string_attr(crate::arkui::attr::font_family(), &v);
        }
    }
    if let Some(v) = num_prop(vm, value, id!(color)) {
        node = node.font_color(v as u32);
    }
    if let Some(v) = num_prop(vm, value, id!(bg)) {
        // On a progress indicator `bg` means the *indicator* colour, not a
        // background fill. The makepad backend already reads it that way (it
        // recolours the arc); ArkUI painted a solid box behind the spinner
        // instead, so Flutter's CircularProgressIndicator — an arc on nothing —
        // came out as a filled purple square.
        match tag.as_str() {
            "loading" => node = node.u32_attr(attr::loading_color(), v as u32),
            "progress" => node = node.u32_attr(attr::progress_color(), v as u32),
            _ => node = node.bg(v as u32),
        }
    }
    if let Some(v) = num_prop(vm, value, id!(radius)) {
        node = node.radius(v as f32);
    }
    if let Some(v) = num_prop(vm, value, id!(pad)) {
        node = node.padding(v as f32);
    }
    if let Some(v) = num_prop(vm, value, id!(margin)) {
        node = node.margin(v as f32);
    }
    // Absolute placement inside a parent aligned top-start, as margin rather
    // than position.
    //
    // ArkUI hit-tests a positioned node where it was *laid out*, not where it
    // draws, so a positioned tap target answers in the wrong place -- an
    // overlay built that way looks right and responds nowhere. Margin is a
    // layout property, so draw and hit-test agree. `web` reads x/y itself, to
    // place a composited surface, and must not be offset twice.
    if tag != "web" {
        let px = num_prop(vm, value, id!(x));
        let py = num_prop(vm, value, id!(y));
        if px.is_some() || py.is_some() {
            let l = px.unwrap_or(0.0) as f32;
            let t = py.unwrap_or(0.0) as f32;
            node = node.f32v_attr(attr::margin(), &[t, 0.0, 0.0, l]);
        }
    }
    if let Some(v) = num_prop(vm, value, id!(border)) {
        node = node.f32v_attr(attr::border_width(), &[v as f32; 4]);
    }
    if let Some(v) = num_prop(vm, value, id!(bordercolor)) {
        node = node.u32_attr(attr::border_color(), v as u32);
    }
    // `value`/`total` mean different attributes on different controls. Setting
    // NODE_PROGRESS_VALUE on an ARKUI_NODE_SLIDER — which is what this used to
    // do for every node — is simply the wrong attribute, so a slider declared at
    // 0.35 sat wherever ArkUI left it while the caption beside it said 0.35.
    let val = num_prop(vm, value, id!(value));
    let total = num_prop(vm, value, id!(total));
    match tag.as_str() {
        "slider" => {
            if let Some(v) = val {
                // The kit expresses slider positions as a 0..1 fraction; ArkUI
                // defaults a slider to 0..100, so pin the range too.
                node = node
                    .f32_attr(attr::slider_min(), 0.0)
                    .f32_attr(attr::slider_max(), total.unwrap_or(1.0) as f32)
                    .f32_attr(attr::slider_value(), v as f32);
            }
        }
        _ => {
            if let Some(v) = val {
                node = node.f32_attr(attr::progress_value(), v as f32);
            }
            if let Some(v) = total {
                node = node.f32_attr(attr::progress_total(), v as f32);
            }
        }
    }
    // `align: n` is ArkUI_Alignment. A Scroll whose content is shorter than its
    // own height centres it by default, which drops the page half way down the
    // screen; `align: 1` (TOP) is what a page wants.
    if let Some(v) = num_prop(vm, value, id!(align)) {
        node = node.i32_attr(attr::alignment(), v as i32);
    }
    // Clip to the node's own box. A stack whose children are placed by margin
    // can be taller than the band it was given, and then it draws over what
    // follows -- which is what put the editorial's kicker on top of its hero.
    if let Some(v) = num_prop(vm, value, id!(clip)) {
        node = node.i32_attr(attr::clip(), v as i32);
    }

    // `on: 1` is the selected state. Which attribute that maps to depends on
    // the control, so it is resolved from the tag rather than the DSL naming
    // three different keys for one concept.
    if let Some(v) = num_prop(vm, value, id!(on)) {
        let on = v as i32;
        match tag.as_str() {
            "checkbox" => {
                node = node
                    .i32_attr(attr::checkbox_select(), on)
                    .u32_attr(attr::checkbox_color(), 0xFF6750A4)
                    // ArkUI draws a checkbox as a CIRCLE by default, which reads
                    // as a radio button. Material's is a rounded square —
                    // `_kEdgeSize` 18 with a RoundedRectangleBorder
                    // (material/checkbox.dart:650). 1 is ROUNDED_SQUARE.
                    .i32_attr(attr::checkbox_shape(), 1);
            }
            "radio" => node = node.i32_attr(attr::radio_checked(), on),
            "toggle" => {
                node = node
                    .i32_attr(attr::toggle_value(), on)
                    .u32_attr(attr::toggle_color(), 0xFF6750A4);
            }
            _ => {}
        }
    }

    // `tap: <id>` wires a click straight back to Rust.
    if let Some(v) = num_prop(vm, value, id!(tap)) {
        node = node.on_event(event::click(), v as i32);
    }
    // A drag, as four ids. The shim measures the gesture on the node that
    // receives it and reports `base + 1..4` -- left, right, up, down -- so a
    // screen declares one base and the host reads a direction off it. Without
    // this the DSL could only ever be tapped, and Wonderous changes wonder by
    // swiping.
    if let Some(v) = num_prop(vm, value, id!(swipe)) {
        node = node.on_event(event::touch(), v as i32);
    }
    // `drift: [dx, dy, ms]` -- move this node by (dx, dy) over ms, natively.
    //
    // The alternative is what this app did first: re-describe the whole screen
    // on a timer. That works, and it caps out around ten frames a second here,
    // because rebuilding an illustration recreates its image nodes faster than
    // they decode. A native animation touches one node's translate and ArkUI
    // interpolates it at the display's own rate, with the tree left alone.
    //
    // The handle is recorded rather than animated here: the node is not mounted
    // yet, and `animate` needs a live one to read a context from.
    if let Some(arr) = prop(vm, value, id!(drift)).and_then(|v| v.as_array()) {
        if let ScriptArrayStorage::ScriptValue(vals) = vm.bx.heap.array_storage(arr) {
            let n: Vec<f64> = vals.iter().filter_map(|v| v.as_number()).collect();
            if n.len() >= 3 {
                DRIFTS.with(|d| {
                    d.borrow_mut()
                        .push((node.raw(), n[0] as f32, n[1] as f32, n[2] as i32))
                });
            }
        }
    }
    // `tapto: "<route>"` is the flutter kit's form of the same thing: a route
    // string rather than a number. Intern it and wire the resulting id.
    if let Some(route) = string_prop(vm, value, id!(tapto)) {
        node = node.on_event(event::click(), intern_route(&route));
    }

    // ---- the flutter kit's layout vocabulary -----------------------------
    // These have no ArkUI spelling of their own; they are makepad's Fill/Fit
    // and per-axis padding, mapped onto percent sizing and the 4-value padding
    // ArkUI does understand.
    // Which ArkUI concept "fill" is depends on the parent's axis. Along the
    // main axis it is flex growth (`layoutWeight`); across it, a full-width or
    // full-height percentage. Mapping both to a 100% size made every child of a
    // row demand the whole row, so the second stat tile vanished off the edge.
    let in_row = parent == "row";
    if num_prop(vm, value, id!(fillw)).unwrap_or(0.0) as i32 == 1 {
        if in_row {
            node = node.f32_attr(attr::layout_weight(), 1.0);
        } else {
            node = node.f32_attr(attr::width_percent(), 1.0);
        }
    }
    if num_prop(vm, value, id!(fillh)).unwrap_or(0.0) as i32 == 1 {
        if in_row {
            node = node.f32_attr(attr::height_percent(), 1.0);
        } else {
            node = node.f32_attr(attr::layout_weight(), 1.0);
        }
    }
    // `padx`/`pady` override `pad` on their axis. ArkUI's padding vector is
    // top, right, bottom, left.
    let padx = num_prop(vm, value, id!(padx));
    let pady = num_prop(vm, value, id!(pady));
    if padx.is_some() || pady.is_some() {
        let base = num_prop(vm, value, id!(pad)).unwrap_or(0.0) as f32;
        let px = padx.map(|v| v as f32).unwrap_or(base);
        let py = pady.map(|v| v as f32).unwrap_or(base);
        node = node.f32v_attr(attr::padding(), &[py, px, py, px]);
    }
    // `elevation` is a Material dp; ArkUI's shadow takes (radius, offsetX,
    // offsetY, ...) so scale it the way the makepad backend does.
    if let Some(e) = num_prop(vm, value, id!(elevation)) {
        let e = e as f32;
        node = node.f32v_attr(attr::shadow(), &[3.0 + e * 2.0, 0.0, 1.0 + e * 0.6, 0.0]);
    }
    // `icon: 1` marks a Font-Awesome glyph. That face ships with the makepad
    // theme; OpenHarmony has no such font, and FA's codepoints sit in the
    // Private Use Area, so pointing font-family at a font that is not there
    // rendered every icon as nothing at all — invisible chevrons, empty FABs.
    // Substituting the nearest glyph that HarmonyOS Sans actually has is the
    // honest fallback: the icon is approximate, but it is visible.
    if num_prop(vm, value, id!(icon)).unwrap_or(0.0) as i32 == 1 {
        if let Some(cp) = string_prop(vm, value, id!(text)) {
            node = node.text(icon_fallback(&cp));
        }
    }
    // `alignx`/`aligny` in 0..=1. For a row the main axis is horizontal, for a
    // column vertical, so which of justify/align-items each drives flips.
    let alignx = num_prop(vm, value, id!(alignx)).map(|v| v as f32);
    let aligny = num_prop(vm, value, id!(aligny)).map(|v| v as f32);
    let bucket = |v: f32| {
        if v < 0.34 {
            0
        } else if v < 0.67 {
            1
        } else {
            2
        }
    };
    match tag.as_str() {
        "row" => {
            if let Some(x) = alignx {
                node = node.i32_attr(attr::row_justify(), bucket(x) + 1);
            }
            if let Some(y) = aligny {
                node = node.i32_attr(attr::row_align(), bucket(y));
            }
        }
        "column" | "scroll" | "list" => {
            if let Some(y) = aligny {
                node = node.i32_attr(attr::col_justify(), bucket(y) + 1);
            }
            // ArkUI's Column centres its children; Flutter's CrossAxisAlignment
            // defaults to start, and so does makepad. Without this every screen
            // came out centre-aligned.
            node = node.i32_attr(attr::col_align(), alignx.map(bucket).unwrap_or(0));
        }
        _ => {}
    }

    // --- children ---------------------------------------------------------
    // `c` is a ScriptArray, NOT an object with a vec — arrays are their own
    // heap type in this VM, so `as_object()` on one yields None and the whole
    // subtree silently disappears.
    // `spacing` has no ArkUI attribute — Column/Row take their gap at creation
    // time, which the node API does not expose. Applying it as a trailing
    // margin on every child but the last is the same picture.
    let spacing = num_prop(vm, value, id!(spacing)).unwrap_or(0.0) as f32;
    let kids = children_of(vm, value);
    // ArkUI's Scroll takes exactly ONE child; everything after the first is
    // dropped on the floor. The DSL (and Flutter, and makepad) all let a
    // scrolling area hold a list of things, so give it the Column it needs.
    // Without this the index rendered its header and nothing else.
    let scroll_wrap = tag == "scroll" && kids.len() > 1;
    let axis = if scroll_wrap { "column" } else { tag.as_str() };
    let last = kids.len().saturating_sub(1);
    let mut built = Vec::new();
    for (i, kid) in kids.into_iter().enumerate() {
        if let Some(mut child) = walk(vm, kid, depth + 1, axis) {
            if spacing > 0.0 && i < last {
                child = match axis {
                    "row" => child.f32v_attr(attr::margin(), &[0.0, spacing, 0.0, 0.0]),
                    _ => child.f32v_attr(attr::margin(), &[0.0, 0.0, spacing, 0.0]),
                };
            }
            built.push(child);
        }
    }
    if scroll_wrap {
        let mut inner = Node::new(ty::column())?
            .f32_attr(attr::width_percent(), 1.0)
            .i32_attr(attr::col_align(), 0);
        for c in built {
            inner = inner.child(c);
        }
        node = node.child(inner);
    } else {
        for c in built {
            node = node.child(c);
        }
    }

    Some(node)
}

/// Nearest system-font glyph for a Font-Awesome codepoint.
///
/// Only the icons the flutter kit actually uses. Anything unmapped falls back
/// to a middle dot rather than the invisible PUA codepoint, so a missing entry
/// shows up as a visible placeholder instead of a hole.
fn icon_fallback(fa: &str) -> &'static str {
    match fa.chars().next().map(|c| c as u32) {
        Some(0xf053) => "\u{2039}",  // chevron-left
        Some(0xf054) => "\u{203A}",  // chevron-right
        Some(0xf067) => "+",         // plus
        Some(0xf00c) => "\u{2713}",  // check
        Some(0xf05e) => "\u{2298}",  // ban
        Some(0xf002) => "\u{2315}",  // search
        Some(0xf004) => "\u{2665}",  // heart
        Some(0xf005) => "\u{2605}",  // star
        Some(0xf013) => "\u{2699}",  // gear
        Some(0xf03a) => "\u{2261}",  // list
        Some(0xf007) => "\u{25CF}",  // user
        Some(0xf02d) => "\u{25A4}",  // book
        Some(0xf015) => "\u{2302}",  // home
        Some(0xf04b) => "\u{25B6}",  // play
        Some(0xf0e7) => "\u{26A1}",  // bolt
        Some(0xf133) => "\u{1F4C5}", // calendar
        Some(0xf3c5) => "\u{25C9}",  // map pin
        Some(0xf15b) => "\u{25A7}",  // file
        _ => "\u{00B7}",
    }
}

/// The `c` array's members, copied out so the walk can borrow the vm again.
fn children_of(vm: &mut ScriptVm, value: ScriptValue) -> Vec<ScriptValue> {
    let Some(c) = prop(vm, value, id!(c)) else {
        return Vec::new();
    };
    let Some(arr) = c.as_array() else {
        return Vec::new();
    };
    match vm.bx.heap.array_storage(arr) {
        ScriptArrayStorage::ScriptValue(v) => v.iter().copied().collect(),
        _ => Vec::new(),
    }
}

fn prop(vm: &mut ScriptVm, obj: ScriptValue, key: LiveId) -> Option<ScriptValue> {
    vm.bx.heap.value_for_apply(obj, key.into(), &Apply::Eval)
}

fn string_prop(vm: &mut ScriptVm, obj: ScriptValue, key: LiveId) -> Option<String> {
    let v = prop(vm, obj, key)?;
    vm.string_with(v, |_vm, s| s.to_string())
}

/// Numbers come back through the VM's own coercion rather than bit-poking the
/// NaN-boxed representation, so ints, floats and colour literals all work.
fn num_prop(vm: &mut ScriptVm, obj: ScriptValue, key: LiveId) -> Option<f64> {
    let v = prop(vm, obj, key)?;
    if v.is_nil() {
        return None;
    }
    let mut out: f64 = 0.0;
    <f64 as ScriptApply>::script_apply(&mut out, vm, &Apply::Eval, &mut Scope::default(), v);
    Some(out)
}
